site_name: Minio Client Documentation
pages:
- ['index.md', Index]
- ['sdks/js/javascript.md', 'SDKs', 'Javascript']
- ['sdks/python/python.md', 'SDKs', 'Python']
- ['contributing.md', 'Contributing', 'Overview']
theme: readthedocs
