site_name: Minio Client Documentation
pages:
- ['index.md', Index]
- ['commands/config.md', 'Commands', 'config']
- ['commands/ls.md', 'Commands', 'ls']
- ['commands/cp.md', 'Commands', 'cp']
- ['commands/mb.md', 'Commands', 'mb']
- ['sdks/js/javascript.md', 'SDKs']
- ['sdks/python/python.md', 'SDKs']
- ['sdks/ruby/ruby.md', 'SDKs']
- ['contributing.md', 'Contributing']
- ['debugging.md', 'Debugging']
theme: readthedocs
